export const enum RouteMap {
  home = '/',
  namespaces = '/namespaces',
  namespace = '/namespaces/:namespace_slug',
  templates = '/templates',
  projects = '/namespaces/:namespace_slug/projects',
  project = '/namespaces/:namespace_slug/projects/:project_slug',
  staff = '/namespaces/:namespace_slug/staff',
  billing = '/namespaces/:namespace_slug/billing',
  services = '/namespaces/:namespace_slug/projects/:project_slug/services',
  networks = '/namespaces/:namespace_slug/projects/:project_slug/networks',
  volumes = '/namespaces/:namespace_slug/projects/:project_slug/volumes',
  configs = '/namespaces/:namespace_slug/projects/:project_slug/configs',
  secrets = '/namespaces/:namespace_slug/projects/:project_slug/secrets',
  deploy = '/namespaces/:namespace_slug/projects/:project_slug/deploy',
  git = '/namespaces/:namespace_slug/projects/:project_slug/git',
  registries = '/namespaces/:namespace_slug/projects/:project_slug/registries',
  team = '/namespaces/:namespace_slug/projects/:project_slug/team',
}
